# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        /opt/hostedtoolcache/Python/3.8.3/x64/bin/python -m pip install --upgrade pip
        /opt/hostedtoolcache/Python/3.8.3/x64/bin/python -m pip install -r requirements.txt
        sudo /opt/hostedtoolcache/Python/3.8.3/x64/bin/python -m spacy download en
        sudo /opt/hostedtoolcache/Python/3.8.3/x64/bin/python -m spacy download de_core_news_sm
        git submodule init
        git submodule update
        wget https://drive.google.com/uc?id=1d-Q-tzGo1RN_YbmvMP5gArQZZdSnclJ0 -O checkpoints/en_de_final.pt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        /opt/hostedtoolcache/Python/3.8.3/x64/bin/python demo.py
